# Generated by Django 2.2.7 on 2019-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_squash'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='characters',
            field=models.ManyToManyField(blank=True, to='comics.Character'),
        ),
        migrations.AddField(
            model_name='issue',
            name='teams',
            field=models.ManyToManyField(blank=True, to='comics.Team'),
        ),
    ]
