# Generated by Django 2.2.7 on 2019-11-29 20:18

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0001_initial"),
    ]

    operations = [UnaccentExtension()]
