# Generated by Django 2.2.7 on 2019-12-04 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_teams_characters_to_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
