# Generated by Django 2.2.7 on 2019-12-02 14:52

import django.contrib.postgres.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='import_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='mod_ts',
        ),
        migrations.RemoveField(
            model_name='seriestype',
            name='modified',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveIntegerField(unique=True, verbose_name='Metron ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('wikipedia', models.CharField(blank=True, max_length=255, verbose_name='Wikipedia Slug')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='team/%Y/%m/%d/')),
                ('creators', models.ManyToManyField(blank=True, to='comics.Creator')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveIntegerField(unique=True, verbose_name='Metron ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('wikipedia', models.CharField(blank=True, max_length=255, verbose_name='Wikipedia Slug')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='character/%Y/%m/%d/')),
                ('alias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('creators', models.ManyToManyField(blank=True, to='comics.Creator')),
                ('teams', models.ManyToManyField(blank=True, to='comics.Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
